### ISSUE TITLE
does not work with beta 2?

### ISSUE THREAD

**Issue by devmondo** [lukeed/fly-concat#1]
hi,
i have this simple task
```
const paths = {
    clientScripts: [`src/client/**/*.js`],
    serverScripts: [`src/server/**/*.js`],
    html: `src/client/**/*.html`,
    merge: ['./jspm_packages/npm/babel-polyfill@6.16.0/dist/polyfill.min.js', './browser.js']
}

exports.concat = function *(o) {
    yield this.source(o.src || paths.merge)
        .concat('all.js')
        .target('');
};

```

but i get this error
```
 TypeError: this.source(...).concat is not a function
```

**Comment by lukeed** [comment]
Hey, make sure that you have the latest beta version of Fly. In one of the beta releases (maybe yours), Fly was incorrectly mounting this plugin as `concat1()`.

**Comment by lukeed** [comment]
Updated my previous comment for clarity's sake.

**Comment by devmondo** [comment]
@lukeed , as always great response, and u r right, i changed it to `concat1` and it worked
but i already did `npm update fly` and it says `2.0.2-beta` what mistake i am doing :)

**Comment by lukeed** [comment]
Remove your current Fly and then reinstall with the beta tag.

```
rm -rf node_modules/fly
npm i --save-dev fly@beta
```

**Comment by lukeed** [comment]
I'm going to go ahead & close this because I know it works (I'm using it). 

it was fixed [here](https://github.com/flyjs/fly/commit/c76691219707569fe2eec02cef3fc5e7aabe0980), so as long as your `fly@beta` reads `2.0.5-beta`, you're set!

**Comment by devmondo** [comment]
@lukeed 
it worked, i really hate NPM sometimes specially on windows !!!, thank you again :)
